### ISSUE TITLE
Killaura detects not hacking players

### ISSUE THREAD

**Issue by dries-c** [DarkWav/SAC#45]
I use version: b18a9cebdccca9c0259917a7d3a2dd8109df4d2f

### Did you change any settings in the Config?

Config modification (YES/NO): Yes
Settings changed: 
  - AKAHAD: 1
  - KillAura-Threshold: 25
  - 
  - 
  - 
  - 
<br><b>[...]</b>

### How to reproduce the issue?

Reproduction: 
use it on a big server network and pvp good

------------------------------------------------------------------------------------------------------

**Comment by DarkWav** [comment]
I Have heared from amy people of this bug now, and im sure this is not afflicted with AKAHAD in any way,
it is the fault of an old aimot check. i try to fix this ASAP.

**Comment by dries-c** [comment]
yeah same that i think 
if you move foreward before you hit and the system calculate the player after you than it detects killaura
or if the player go after a wall

**Comment by DarkWav** [comment]
Fixed with 3.2.3 :) sorry for my inactivity but i had exams coming up.

**Comment by Guillaume351** [comment]
@DarkWav Not really fixed :/ if you hit fast (with two fingers or on windows 10) it will kick you for Aura

**Comment by DarkWav** [comment]
also if AKAHAD is disabled?

**Comment by Guillaume351** [comment]
@DarkWav I just tested with AKAHAD off, and it still do it :/ If you want to reproduce on a mobile device, just hit with two of your fingers fast on the screen

**Comment by DarkWav** [comment]
AH thank god if it is not afflicted with AKAHAD it is easy to fix :)

**Comment by DarkWav** [comment]
HOPEFULLY fixed with 3.2.5. If not, please reply.
